import type { FoodItem } from "./types";

const now = new Date('2030-01-01T00:00:00Z');

export const mockFoodItems: FoodItem[] = [
  {
    id: '1',
    name: 'Veg Biryani',
    source: 'Radha Krishna Hotel',
    type: 'Veg',
    originalPrice: 250,
    discountedPrice: 100,
    expiryTime: new Date(now.getTime() + 2 * 60 * 60 * 1000).toISOString(),
    preparedTime: new Date(now.getTime() - 1 * 60 * 60 * 1000).toISOString(),
    imageId: 'veg-biryani',
    quantity: 10,
    rating: 4.5,
    status: 'Available',
    condition: 'Fresh',
    verified: true,
  },
  {
    id: '2',
    name: 'Sambar & Rice Combo',
    source: 'Hostel Mess',
    type: 'Veg',
    originalPrice: 120,
    discountedPrice: 40,
    expiryTime: new Date(now.getTime() + 1 * 60 * 60 * 1000).toISOString(),
    preparedTime: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    imageId: 'sambar',
    quantity: 15,
    rating: 4.2,
    status: 'Available',
    condition: 'Safe for Human Consumption',
    verified: true,
  },
  {
    id: '3',
    name: 'Parotta (2 pcs) with Kurma',
    source: 'Nalabagam Canteen',
    type: 'Veg',
    originalPrice: 80,
    discountedPrice: 35,
    expiryTime: new Date(now.getTime() + 3 * 60 * 60 * 1000).toISOString(),
    preparedTime: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
    imageId: 'parotta',
    quantity: 8,
    rating: 4.8,
    status: 'Limited',
    condition: 'Fresh',
    verified: true,
  },
  {
    id: '4',
    name: 'Gobi Fried Rice',
    source: 'Madurai Lee Corner',
    type: 'Veg',
    originalPrice: 180,
    discountedPrice: 90,
    expiryTime: new Date(now.getTime() + 45 * 60 * 1000).toISOString(),
    preparedTime: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
    imageId: 'fried-rice',
    quantity: 5,
    rating: 4.6,
    status: 'Available',
    condition: 'Fresh',
    verified: false,
  },
    {
    id: '5',
    name: 'Mushroom Biryani',
    source: 'Radha Krishna Hotel',
    type: 'Veg',
    originalPrice: 280,
    discountedPrice: 120,
    expiryTime: new Date(now.getTime() + 2 * 60 * 60 * 1000).toISOString(),
    preparedTime: new Date(now.getTime() - 1 * 60 * 60 * 1000).toISOString(),
    imageId: 'veg-biryani',
    quantity: 7,
    rating: 4.7,
    status: 'Available',
    condition: 'Fresh',
    verified: true,
  },
  {
    id: '6',
    name: 'Rasam & Rice Combo',
    source: 'Hostel Mess',
    type: 'Veg',
    originalPrice: 100,
    discountedPrice: 30,
    expiryTime: new Date(now.getTime() + 1 * 60 * 30 * 1000).toISOString(),
    preparedTime: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    imageId: 'sambar',
    quantity: 20,
    rating: 4.1,
    status: 'Available',
    condition: 'Safe for Human Consumption',
    verified: false,
  },
  {
    id: '7',
    name: 'Vegetable Peelings & Scraps',
    source: 'Central Kitchen',
    type: 'Veg',
    originalPrice: 50,
    discountedPrice: 0,
    expiryTime: new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString(),
    preparedTime: new Date(now.getTime() - 3 * 60 * 60 * 1000).toISOString(),
    imageId: 'vegetable-scraps',
    quantity: 50,
    rating: 3.0,
    status: 'Available',
    condition: 'Only for Animal Feed',
    verified: true,
  },
  {
    id: '8',
    name: 'Stale Bread Loaves',
    source: 'Bakery Outlet',
    type: 'Veg',
    originalPrice: 100,
    discountedPrice: 10,
    expiryTime: new Date(now.getTime() + 48 * 60 * 60 * 1000).toISOString(),
    preparedTime: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
    imageId: 'stale-bread',
    quantity: 30,
    rating: 3.5,
    status: 'Available',
    condition: 'Only for Animal Feed',
    verified: false,
  },
  {
    id: '9',
    name: 'Leftover Cooked Rice',
    source: 'Community Kitchen',
    type: 'Veg',
    originalPrice: 40,
    discountedPrice: 10,
    expiryTime: new Date(now.getTime() + 12 * 60 * 60 * 1000).toISOString(),
    preparedTime: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    imageId: 'cooked-rice',
    quantity: 25,
    rating: 4.0,
    status: 'Available',
    condition: 'Safe for Human Consumption',
    verified: false,
  }
];
